name: Build PlatformIO Firmware

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install PlatformIO Core
      run: |
        python3 -c "$(curl -fsSL https://raw.githubusercontent.com/platformio/platformio/master/scripts/get-platformio.py)"
        echo "$HOME/.platformio/penv/bin" >> $GITHUB_PATH

    - name: Build firmware
      run: |
        platformio run

    - name: Upload firmware
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: .pio/build/bluepill_f103c8/*.hex
